### ISSUE TITLE
don't waste time trying to monetize hangman

### ISSUE THREAD

**Issue by StoneCypher** [Ehawk82/hangman#19]
nobody is going to put money into hangman.  don't waste the time

**Comment by Ehawk82** [comment]
ok

**Comment by Ehawk82** [comment]
just worth the mention...

I wasn't planning on making a profit, but rather, trying to give myself an opportunity to attempt to make IAP's   Eventually i am going to have to learn that kind of stuff.  I digress

**Comment by StoneCypher** [comment]
ya one thing at a time though

right now you're learning to release fast

next is tooling

**Comment by Ehawk82** [comment]
I'm sorta stuck on using word-list with rollup currently.  I have a habit of feeling the need to figure things out on my own...(I know ugh)

I've been spending my time watching tutorials and can figure out how to get a startup library going, but I haven't been able to do it with the word-list module.  

Once I get passed this hurdle, the remainder of development should be pretty quick like with TTT
